index.ts
src/isEmpty.test.ts
src/isEmpty.ts
src/isNil.ts
src/keys.test.ts
src/keys.ts
src/size.test.ts

- lodash 의 클론을 만드는게 목적이라, lodash 와 결과가 다른 친구들의 내부 코드를 수정했습니다
- lodash 동작과 일치하는지 확인하기 위해 테스트 코드를 추가헀습니다.

lodash 와 비교 및 동작 일치

---

package.json
src/has.bench.ts
src/has.test.ts
src/has.ts
vite.config.ts

this closes #9 
has 메서드를 추가합니다.

[#9] 🚀 has

---

.changeset/orange-icons-brush.md
index.ts
package.json
src/throttle.test.ts
src/throttle.ts

🚀 throttle

---

.changeset/yellow-hounds-work.md
index.ts
package.json
src/debounce.test.ts
src/debounce.ts

🚀 debounce

---

.changeset/brave-needles-bow.md
index.ts
package.json
src/clamp.bench.ts
src/eq.ts
src/every.bench.ts
src/every.test.ts
src/every.ts
src/includes.bench.ts
src/includes.test.ts
src/includes.ts
src/isNull.ts

:rocket: eq , includes, every, isNull

---

.changeset/eleven-webs-do.md
index.ts
package.json
src/before.test.ts
src/before.ts
src/isNumber.test.ts
src/isNumber.ts
src/merge.bench.ts
src/merge.test.ts
src/merge.ts
src/omit.bench.ts
src/omit.test.ts
src/omit.ts
src/once.test.ts
src/once.ts

this closes #53
this closes #108 
this closes #58 
this closes #67

🚀 merge, isNumber, once, before

---

.github/workflows/validate-utils-registration.yml
index.ts
package.json
scripts/generate-utils.mjs

🧪 validate utils registration

---

.github/workflows/benchmark-to-comment.yml
.github/workflows/benchmark-to-markdown.yml
.github/workflows/ci.yaml
.gitignore
scripts/benchmark-to-md.mjs
src/debounce.ts
vitest.config.ts

this closes #114 
- src 파일 정보가 변경되는 경우 벤치마크 댓글을 생성합니다.

🧪 benchmark

---

.changeset/sixty-lands-feel.md
.eslintrc
index.ts
package.json
src/isString.test.ts
src/isString.ts
src/mapValues.bench.ts
src/mapValues.test.ts
src/mapValues.ts

this closes #82 
this closes #47
기존 저희 내부 유틸 가져왔습니다~

🚀 mapValues

---

.changeset/hip-dancers-guess.md
index.ts
package.json
src/cloneDeep.bench.ts
src/cloneDeep.test.ts
src/cloneDeep.ts
src/toNumber.bench.ts

🚀 cloneDeep

---

.changeset/poor-geese-flow.md
index.ts
package.json
src/isUndefined.ts

🚀 isUndefined

---

.changeset/huge-snakes-add.md
index.ts
package.json
src/findLastIndex.bench.ts
src/findLastIndex.test.ts
src/findLastIndex.ts
src/internal/baseIteratee.test.ts
src/internal/baseIteratee.ts

성능을 개선하는 길은 험하구나...ㅇ<-< 분명 8시에 시작했는데..

🚀 findLastIndex

---

.changeset/smooth-camels-yell.md
index.ts
package.json
src/internal/to-string-tags.ts
src/isString.ts
src/size.ts
src/toString.bench.ts
src/toString.test.ts
src/toString.ts

- this closes #60 
- add return type of `isString`

🚀 toString

---

.changeset/violet-worlds-call.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/detect-changed-packages.yml
README.md
index.ts
package.json
src/findIndex.bench.ts
src/findIndex.test.ts
src/findIndex.ts

fromIndex에 null을 대응하는게 맞을지 여쭙습니다.
ts 상으로는 null이 비허용되는데 js에는 충분히 들어올 법도 해서 고민입니다 🤔

🚀 findIndex

---

.github/workflows/detect-changed-packages.yml

detect changed packages의 언어를 영어로 변경합니다

[공통] detect changed packages의 언어를 영어로 변경합니다

---

.changeset/cold-jars-wait.md
.changeset/dull-horses-bet.md
.changeset/free-pillows-stay.md
.changeset/huge-snakes-add.md
.changeset/lemon-regions-accept.md
.changeset/petite-impalas-kiss.md
.changeset/poor-geese-flow.md
.changeset/smooth-camels-yell.md
.changeset/violet-worlds-call.md
CHANGELOG.md
package.json

-   79010c6: 🚀 lt
[🚀 lt](https://github.com/NaverPayDev/hidash/pull/136)
-   2ecbab5: 🚀 clone
PR: [\[#46\] 🚀 clone](https://github.com/NaverPayDev/hidash/pull/148)
-   acae386: 🚀 `shuffle`
[🚀 shuffle](https://github.com/NaverPayDev/hidash/pull/130)
-   57bb04d: 🚀 `findLastIndex`
PR: [🚀 findLastIndex](https://github.com/NaverPayDev/hidash/pull/140)
-   9158811: 🚀 `first` `last` `isPlainObject` `head`
[🚀 `first` `last` `isPlainObject` `head`](https://github.com/NaverPayDev/hidash/pull/132)
-   63535c4: 🚀 `isFunction`
[🚀 isFunction, node>=18.12.0](https://github.com/NaverPayDev/hidash/pull/134)
-   4bd8011: 🚀 `isUndefined`
PR: [🚀 isUndefined](https://github.com/NaverPayDev/hidash/pull/135)
-   d892636: 🚀 `toString`
[🚀 toString](https://github.com/NaverPayDev/hidash/pull/137)
-   505d2d9: 🚀 …

🚀 version changed packages

---

.changeset/common-aliens-melt.md
index.ts
package.json
src/internal/baseIteratee.ts
src/internal/types.ts
src/uniq.bench.ts
src/uniq.test.ts
src/uniq.ts
src/uniqBy.bench.ts
src/uniqBy.test.ts
src/uniqBy.ts

this closes #69 
this closes #70

🚀 uniq, uniqBy

---

.changeset/all-spies-hide.md
index.ts
package.json
src/transform.bench.ts
src/transform.test.ts
src/transform.ts

🚀 transform

---

.changeset/quiet-cloths-nail.md
src/every.ts
src/filter.ts
src/findIndex.ts
src/findLastIndex.ts
src/flatten.ts
src/groupBy.bench.ts
src/groupBy.test.ts
src/groupBy.ts
src/includes.ts
src/internal/baseIteratee.test.ts
src/internal/baseIteratee.ts
src/internal/baseIteratee.type.ts
src/internal/types.ts
src/map.ts
src/pick.ts
src/some.test.ts
src/some.ts
src/uniqBy.test.ts
src/uniqBy.ts

🧪 support groupBy by string with dot 

---

.changeset/fair-wolves-fail.md
src/every.test.ts
src/every.ts
src/some.test.ts

apply baseIteratee in every

---

.changeset/shaggy-comics-sniff.md
src/sumBy.ts

🔧 refactor sumby with baseIteratee

---

.changeset/ripe-insects-switch.md
index.ts
package.json
src/range.bench.ts
src/range.test.ts
src/range.ts

[#198] 🚀 range

---

.changeset/small-numbers-visit.md
index.ts
package.json
src/identity.test.ts
src/identity.ts

[#195] 🚀 identity

---

.changeset/cyan-clowns-dream.md
package.json

🐛 fix wrong glob pattern

---

.github/workflows/benchmark-to-comment.yml

fix: properly handle PR number for workflow_dispatch event

---

package.json
pnpm-lock.yaml

⬆️ update packages

---

.github/workflows/benchmark-to-comment-test.yml

테스트 버전의 benchmark action 을 추가합니다.
기존 benchmark action 과 동일한 버전으로 동작한다면,
이후 action 로직을 변경합니다.

[action] add benchmark action

---

.github/workflows/validate-utils-registration.yml

This is test changes to run action on pull request's head branch.

🧪 Fetch $GITHUB_BASE_REF on github action

---

.github/workflows/validate-utils-registration.yml

🧪 Fix action (2)

---

.changeset/thirty-turtles-roll.md
index.ts
package.json

#219 
add missing zip
@yujeong-jeon 님, 문제 해결되기 전까지는 해당 액션 disable 처리하겠습니다.

🐛 add missing zip

---

.changeset/plain-squids-crash.md
src/isNil.ts

null 이나 undefined 로 type guard 를 할 수 있도록 수정해보았습니다.
type/check 에 한번에 모와서 병합 pr 을 생성하려고 합니다.

isNill type fix

---

.changeset/plain-squids-crash.md
src/eq.ts
src/filter.ts
src/isNil.ts
src/range.ts

- 이전 PR 의 isNil 의 null, undefined
- eq 의 any 제거 및 boolean 반환
- range 의 number 배열 반환
- lodash import 제거

type fix isNill, eq, range

---

src/before.bench.ts

Added before.bench.ts for performance comparison with lodash

feat: add benchmark for before

---

.changeset/shaky-steaks-itch.md
src/repeat.test.ts
src/repeat.ts

repeat: Update repeat function to handle MAX_SAFE_INTEGER edge cases for `n`

---

src/repeat.ts

This is a simple example of hidash's commenting guideline I suggested.
1. The header comment should succinctly describe the function’s purpose and must include `params` and `returns` information.
2. For major logic improvements that enhance performance compared to lodash, please add a comment directly above the relevant code explaining the improvement point.
Thank you for reviewing the entire code in the file changes.
Below is an example of how the comments are displayed in the VSCode IDE (see the attached image):

Update comment for repeat function

---

.github/workflows/canary.yml
.github/workflows/rc.yml

> Same as https://github.com/NaverPayDev/pie/issues/152
All tests have been completed in pie.

Add workflows for Release Canary and Release RC 

---

.github/workflows/canary.yml
.github/workflows/rc.yml
package.json

Fix canary.yml, rc.yml

---

.github/workflows/canary.yml
.github/workflows/rc.yml
package.json

Fit the entire repository convention. Please run the build in workflow.

Add build step to workflows for canary, rc, and release processes

---

src/eq.ts
src/every.ts
src/first.ts
src/flatten.ts
src/flow.ts

add comments eq, every, first, flatten, flow
