NaverPayDev/hidash

- .changeset/eleven-webs-do.md
- CHANGELOG.md
- package.json
-   0d3de8e: 🚀 `merge`, `isNumber`, `once`, `before`, `omit`
[\[#53\] 🚀 merge](https://github.com/NaverPayDev/hidash/pull/107)
> 🚀 version changed packages

- vite.config.mts
- `es.array.push`와 같이 구현자체는 오래되었으나 엔진 버그등으로 인해 core-js 에서 폴리필이 추가되는 경우가 있습니다.
- 이러한 경우에는 hidash, pite 모두 폴리필이 추가되지 않았으면 합니다. 의견 부탁드립니다!
- 버그가 발생할 동작을 사용하지 않음
- 아주 지극히 예외 적인 상황에서만 발생하는 오류: 폴리필 추가 비용이 더 쓸모없음
- 나머지 애들은 실제로 현재 범위에서 지원하지 않는 메서드로 예외 처리 필요 ;ㅁ;
```js
// 1. 빈 배열 생성
const arr = [];
// 2. 배열의 length를 비작성 가능(non-writable)으로 설정
Object.defineProperty(arr, 'length', { writable: false });
// 3. push()를 호출 (인자를 전달하지 않음)
arr.push(); // 기존 Chrome에서는 오류가 발생하지 않음 (무시됨)
// 그러나 명세에 따르면 `length` 속성은 업데이트하려다 실패해야 하고, TypeError를 던져야 함.
```
```js
// 스파스 배열 생성
const sparseArray1 = [ , ];  // sparse array, 길이 1
const sparseArray2 = Array(1);  // 동일한 sparse array 생성 방식
// includes(undefined) 호출
console.log(sparseArray1.includes(undefined)); // true, 올바른 동작 …
```
> 📝 Add comments on why exceptions are needed

- .eslintrc
- src/mapValues.ts
- src/omit.ts
- src/shuffle.ts
- vite.config.mts
- Implement it in a different way without using `fromEntries` and `flatMap`.
- `trim` is confirmed as a usable ES5 method , so it will be added to the usage list. (Found information about a Safari bug, but couldn't locate the exact bug issue 😭 see comments).
> remove some polyfill from allow list

- .changeset/huge-lions-look.md
- index.ts
- package.json
- src/difference.bench.ts
- src/difference.test.ts
- src/difference.ts
> 🚀 difference

- .changeset/good-knives-write.md
- src/has.ts
- src/internal/types.ts
- src/omit.ts
#89
- PropertyPath 를 별도 타입으로 분리
- lodash 와 동일하게 타입을 더 좁힙니다.
> 🔧PropertyPath 로 분리

- src/cloneDeep.test.ts
- src/cloneDeep.ts
This PR fixes an issue where the `cloneDeep` function was not properly preserving the prototype chain when cloning class instances. The previous implementation treated class instances as plain objects, which resulted in losing the class type information during cloning.
- Modified the object cloning logic to preserve prototype chain using `Object.getPrototypeOf` and `Object.create`
- Added comprehensive test cases to verify class instance cloning behavior
- Ensured compatibility with lodash's `cloneDeep` implementation
Added a new test suite that verifies:
- Proper cloning of class instances
- Preservation of constructor and prototype chain
- Consistency with lodash's behavior
```typescript
class User {
name: string
constructor(name: string) {
this.name = name
}
}
const user = new …
```
> fix: Preserve class prototype chain in cloneDeep function

- src/cloneDeep.bench.ts
- src/cloneDeep.test.ts
- src/internal/noop.test.ts
- src/internal/noop.ts
- src/isEmpty.test.ts
- src/isError.test.ts
- src/isFunction.test.ts
- src/isPlainObject.test.ts
- src/memoize.test.ts
- src/shuffle.test.ts
- src/size.test.ts
- src/toPairs.test.ts
This PR adds a `noop` utility function that implements the existing `Noop` type. The function is a common utility that can be used wherever an empty function callback is needed, improving code readability and reusability.
- Add `noop` utility function
- Apply `noop` function in test files instead of empty arrow functions
- Add test cases for `noop` function
> feat: Add noop function

- .github/workflows/detect-changed-packages.yml
- .github/workflows/validate-utils-registration.yml
fix github action evnet type from 'pull_request' to 'pull_request_target'
see: https://docs.github.com/ko/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> 🔧 fix event target

- .changeset/fuzzy-wolves-study.md
- src/mapValues.ts
This pull request updates the `mapValues` function to utilize `baseIteratee`. This change improves the function's flexibility and allows it to handle a wider range of iteratee types.
-   The `mapValues` function now uses `baseIteratee` to handle iteratee arguments.
-   This change ensures that the iteratee is properly converted to a function before being used.
-   This update enhances the `mapValues` function's ability to work with various iteratee types, including functions, objects, and property strings.
-   Improved flexibility in handling different iteratee types.
-   More robust and reliable `mapValues` function.
-   Fixes #189
Please review and merge this pull request to incorporate the changes into the main branch.
> Update `mapValues` with `baseIteratee`

- .changeset/fair-teeth-refuse.md
- vite.config.mts
There is polyfill injection bug in `uniq.(mjs | js)`
```js
// uniq.mjs
import s from "core-js-pure/features/instance/push.js";
```
When users use `uniq` function in their code, this error occured because hidash does not have `core-js-pure` as deps:
```
Error: Cannot find module 'core-js-pure/features/instance/push.js'
```
> Fix vite.config.mts

- .changeset/rare-cougars-see.md
- src/merge.test.ts
- src/merge.ts
This pull request addresses issue #222 by adding null and undefined checks to the first parameter of the `merge` function in `hidash`.  This prevents potential errors when the function is called with a null or undefined value as the first argument.
**Summary of Changes:**
*   [x] Added checks for null and undefined values in the first parameter of the `merge` function.
*   [x] Ensures that the `merge` function handles cases where the first parameter is null or undefined without returning `undefined` (same as lodash)
**Related Issue:**
*   Closes #222
> Fix Issue #222: Handle null/undefined in `merge` function

- .changeset/bumpy-beds-chew.md
- src/every.test.ts
- src/filter.test.ts
- src/findIndex.bench.ts
- src/findIndex.test.ts
- src/findLastIndex.bench.ts
- src/findLastIndex.test.ts
- src/groupBy.bench.ts
- src/groupBy.test.ts
- src/internal/baseIteratee.test.ts
- src/internal/baseIteratee.ts
- src/internal/baseIteratee.type.ts
- src/mapValues.bench.ts
- src/mapValues.test.ts
- src/pickBy.test.ts
- src/some.test.ts
- src/sumBy.bench.ts
- src/sumBy.test.ts
- src/uniqBy.test.ts
This PR removes the `PropertyName (string | number | symbol)` typed IterateeShorthand to simplify and improve type safety. 
- Simplify the IterateeShorthand implementation by removing the PropertyName type.
- Ensure that the changes align with project standards and maintain high performance.
- Removed the `PropertyName` typed IterateeShorthand.
- Updated relevant tests to reflect this change.
- Verified performance through benchmarks.
> 💥 Remove `PropertyName` typed IterateeShorthand

- .changeset/sharp-symbols-check.md
- src/difference.ts
- src/filter.ts
- src/flow.ts
- src/groupBy.ts
- src/has.ts
- src/internal/baseIteratee.ts
- src/omit.ts
- src/shuffle.ts
- src/some.ts
- src/sum.ts
- src/transform.ts
- src/union.ts
- src/uniqBy.ts
for 문을 만족하는 조건을 확인할때 배열의 length 를 직접 사용하게 되면, 해당 배열의 length 를 참조하는데 일정 비용이 드는 것으로 알고 있습니다.
하여 이를 array.length 를 변수에 저장해두고 사용해두면 참조하는 비용을 줄일 수 있을것으로 기대됩니다.
- BenchmarkREADME 에 있는 결과 보다 나아졌는가?
- 나아진 부분도 있고 떨어진 부분도 있지만, 결과적으로 더 나은 방향으로 결정
- action 이 동일하게 동작하는 부분 확인완료
- comment 가 업데이트 되지 않는 부분이 있는 것 같아 다음 PR 에서 확인 필요
> length check one time

- README.md
> fix: update CI badge URL in README

- src/isArray.bench.ts
- src/isArray.test.ts
- Added isArray.test.ts for verifying functionality
- Added isArray.bench.ts for performance comparison with lodash
**Test**
**Benchmark**
> feat: add unit tests and benchmark for isArray

- src/isFunction.bench.ts
Added isFunction.bench.ts for performance comparison with lodash
> feat: add benchmark for isFunction

- src/assign.ts
- src/entries.ts
- src/filter.ts
- src/findIndex.ts
- src/findLastIndex.ts
- src/isEqual.ts
- src/isFunction.ts
- src/isMap.ts
- src/isSet.ts
- src/pickBy.ts
- src/some.ts
- src/toPairs.ts
- src/unzip.ts
- src/values.ts
- src/zip.ts
This pull request adds comprehensive JSDoc comments to various utility functions to improve code readability, maintainability, and developer experience. The changes include:
- Added JSDoc comments for multiple utility functions.
- Enhanced clarity by documenting function purposes, parameters, and return types.
- Updated existing JSDoc comments for consistency and accuracy.
- Added perfomance-related comments on implementation if needed.
- Added JSDoc comments to utility functions I implemented so far.
- Modified `entries` to use `toPairs` directly and added JSDoc for clarity.
> Added JSDoc comments for utility functions I implemented.

- src/first.bench.ts
Added first.bench.ts for performance comparison with lodash
> feat: add benchmark for first

- src/isMap.bench.ts
- src/isMap.test.ts
- Added isMap.test.ts for verifying functionality
- Added isMap.bench.ts for performance comparison with lodash
> feat: add unit tests and benchmark for isMap

- src/last.bench.ts
- src/last.test.ts
Added `last.bench.ts` for performance comparison with Lodash.  
Removed duplicated test cases from `last.test.ts`.
> feat: add benchmark for last 

- src/before.ts
- src/chunk.ts
- src/clamp.ts
- src/clone.ts
- src/cloneDeep.ts
This PR updates inline documentation for key utility functions by adding JSDoc headers and internal comments. The main goal is to boost code readability and maintainability, ensuring consistency with our commenting guidelines.
No functional code has been changed.
**Functions Updated:**
- `before`
- `chunk`
- `clamp`
- `clone` (shallow clone)
- `cloneDeep`
The new comments clarify each function's purpose, parameters, return values, and important implementation details or limitations.
> docs: Enhance JSDoc and internal comments for core utility functions

- src/isNumber.bench.ts
- Added isNumber.bench.ts for performance comparison with lodash
> feat: add benchmark for isNumber function
